// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLz9yFuSzmEOMLwjSOiRJddEveG5vk1Jc',
    appId: '1:199568266847:web:f4bdde53aadd0044a7adea',
    messagingSenderId: '199568266847',
    projectId: 'subvault',
    authDomain: 'subvault.firebaseapp.com',
    storageBucket: 'subvault.firebasestorage.app',
    measurementId: 'G-28P5P8KV3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRDPBdU3lv61NXO_SrBX7s3KnMFnDXdq8',
    appId: '1:199568266847:android:ec43e0bf0e118c16a7adea',
    messagingSenderId: '199568266847',
    projectId: 'subvault',
    storageBucket: 'subvault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3lwIOH8SJ3h8CWbJFgKysBZabb5wHtTY',
    appId: '1:199568266847:ios:8d043854845c924ba7adea',
    messagingSenderId: '199568266847',
    projectId: 'subvault',
    storageBucket: 'subvault.firebasestorage.app',
    iosClientId: '199568266847-lu4i0rsjpp9rpl222qcg62jk6cbh90v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.subvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3lwIOH8SJ3h8CWbJFgKysBZabb5wHtTY',
    appId: '1:199568266847:ios:8d043854845c924ba7adea',
    messagingSenderId: '199568266847',
    projectId: 'subvault',
    storageBucket: 'subvault.firebasestorage.app',
    iosClientId: '199568266847-lu4i0rsjpp9rpl222qcg62jk6cbh90v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.subvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLz9yFuSzmEOMLwjSOiRJddEveG5vk1Jc',
    appId: '1:199568266847:web:7f91e92199b16774a7adea',
    messagingSenderId: '199568266847',
    projectId: 'subvault',
    authDomain: 'subvault.firebaseapp.com',
    storageBucket: 'subvault.firebasestorage.app',
    measurementId: 'G-FCZ5RRV1L6',
  );
}
